---
title: "Severe weather events,  population health and economic consequences"
author: "Chahid Azarkan"
output: 
  html_document: 
    keep_md: yes
---

#Synopsis


#Introduction
Severe weather events, like storms, can cause problems in different communites and municipalities to both public health and the economy. Preventing the effect of severe weather events is a key concern for the federal, state and municipal governments.

In this analysis data is used from the U.S. National Oceanic and Atmospheric Administration's (NOAA) storm database. In this database characteristics are tracked of major weather events in the United States, including when and where they occur, as well as estimates of any fatalities, injuries, and property damage.

This analysis is answers the following two questions:

1. Across the United States, which types of events are most harmful with respect to population health?
2. Across the United States, which types of events have the greatest economic consequences?


#Data processing
The following libraries are used for this analyis:
```{R}
library(dplyr)
library(data.table)
```


To be able to carry out the analysis the data needs to be donwloaded and imported.
```{R import, cache=TRUE}
fileUrl <- "https://d396qusza40orc.cloudfront.net/repdata%2Fdata%2FStormData.csv.bz2"
temp <- tempfile()
download.file(fileUrl,temp, method="curl")
weather <- read.csv(temp, "household_power_consumption.txt"), sep = ";")
unlink(temp)
```



There should be a section titled Data Processing which describes (in words and code) how the data were loaded into R and processed for analysis. In particular, your analysis must start from the raw CSV file containing the data. You cannot do any preprocessing outside the document. If preprocessing is time-consuming you may consider using the Cache=TRUE??????? option for certain code chunks.


#Data analysis
Does the analysis address the question of which types of events are most harmful to population health?
Does the analysis address the question of which types of events have the greatest economic consequences?


#Results







